apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.frontendService.name }}
    {{ include "shopcart.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.frontendService.name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.frontendService.port }}
  type: ClusterIP